export const dynamic = 'force-dynamic';
/**
 * Generic Daily Briefing Cron
 * POST /api/cron/daily-briefing
 *
 * Runs for any org — replaces the Thrive-only hardcoded briefing.
 * Collects all active playbook-generated artifacts and posts an actionable
 * Slack briefing with Approve/Decline buttons via Uncle Elroy.
 *
 * Cloud Scheduler (per org):
 *   gcloud scheduler jobs create http {orgSlug}-daily-briefing \
 *     --schedule="30 8 * * *" --time-zone="{orgTimezone}" \
 *     --uri="https://<domain>/api/cron/daily-briefing" \
 *     --http-method=POST \
 *     --headers="Authorization=Bearer $CRON_SECRET,Content-Type=application/json" \
 *     --message-body='{"orgId":"org_thrive_syracuse"}'
 */

import { NextRequest, NextResponse } from 'next/server';
import { getAdminFirestore } from '@/firebase/admin';
import { Timestamp } from '@google-cloud/firestore';
import { requireCronSecret } from '@/server/auth/cron';
import { elroySlackService } from '@/server/services/communications/slack';
import { buildDailyBriefingBlocks } from '@/server/services/insights/artifact-slack-blocks';
import { logger } from '@/lib/logger';
import type { InboxArtifact } from '@/types/inbox';

export const maxDuration = 300;

export async function POST(request: NextRequest) {
    const authError = await requireCronSecret(request, 'daily-briefing');
    if (authError) return authError;

    let body: { orgId?: string } = {};
    try {
        body = await request.json();
    } catch {
        // Empty body is OK — we'll discover all active orgs
    }

    const orgId = body.orgId;

    try {
        if (orgId) {
            const result = await runBriefingForOrg(orgId);
            return NextResponse.json(result);
        }

        // No orgId — run for all orgs with active playbooks
        const orgs = await getOrgsWithActivePlaybooks();
        const results = await Promise.allSettled(
            orgs.map(id => runBriefingForOrg(id))
        );

        const summary = results.map((r, i) => ({
            orgId: orgs[i],
            status: r.status,
            ...(r.status === 'fulfilled' ? r.value : { error: (r as PromiseRejectedResult).reason?.message }),
        }));

        return NextResponse.json({ success: true, orgs: summary });
    } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        logger.error('[DailyBriefing] Failed', { error: msg, orgId });
        return NextResponse.json({ success: false, error: msg }, { status: 500 });
    }
}

export async function GET(request: NextRequest) {
    return POST(request);
}

// ============================================================================
// Core Briefing Runner
// ============================================================================

async function runBriefingForOrg(orgId: string): Promise<{
    success: boolean;
    artifactCount: number;
    slackTs?: string;
    error?: string;
}> {
    const db = getAdminFirestore();
    const now = new Date();

    logger.info('[DailyBriefing] Running for org', { orgId });

    // 1. Load org config
    const tenantDoc = await db.collection('tenants').doc(orgId).get();
    const tenant = tenantDoc.data() ?? {};
    const orgName = (tenant.name as string) ?? (tenant.businessName as string) ?? orgId;
    const orgSlug = (tenant.slug as string) ?? orgId.replace('org_', '');
    const slackChannel = (tenant.slackChannel as string) ?? `#${orgSlug}-pilot`;

    // 2. Collect today's actionable artifacts (generated by insight crons)
    const startOfDay = new Date(now);
    startOfDay.setHours(0, 0, 0, 0);

    const artifactsSnap = await db
        .collection('tenants')
        .doc(orgId)
        .collection('inbox_artifacts')
        .where('createdAt', '>=', Timestamp.fromDate(startOfDay))
        .orderBy('createdAt', 'desc')
        .limit(20)
        .get();

    const artifacts: InboxArtifact[] = artifactsSnap.docs.map(doc => ({
        id: doc.id,
        ...doc.data(),
    } as InboxArtifact));

    // Also include pending artifacts from previous days that haven't been decided
    const pendingSnap = await db
        .collection('tenants')
        .doc(orgId)
        .collection('inbox_artifacts')
        .where('status', '==', 'pending_review')
        .orderBy('createdAt', 'desc')
        .limit(10)
        .get();

    const pendingArtifacts: InboxArtifact[] = pendingSnap.docs
        .filter(doc => !artifacts.some(a => a.id === doc.id))
        .map(doc => ({ id: doc.id, ...doc.data() } as InboxArtifact));

    const allArtifacts = [...artifacts, ...pendingArtifacts];

    if (allArtifacts.length === 0) {
        logger.info('[DailyBriefing] No artifacts to report', { orgId });
        return { success: true, artifactCount: 0 };
    }

    // 3. Build Slack blocks
    const blocks = buildDailyBriefingBlocks(allArtifacts, {
        orgName,
        orgSlug,
    });

    // 4. Ensure Slack channel exists
    const channelName = slackChannel.replace(/^#/, '');
    let channelId: string | undefined;
    const existing = await elroySlackService.findChannelByName(channelName);
    if (existing) {
        channelId = existing.id;
    } else {
        const created = await elroySlackService.createChannel(channelName);
        channelId = created?.id;
    }
    if (channelId) {
        await elroySlackService.joinChannel(channelId);
    }

    // 5. Post briefing
    const fallbackText = `Daily Briefing — ${orgName} — ${now.toLocaleDateString('en-US', { weekday: 'long', month: 'short', day: 'numeric' })}`;
    const postResult = await elroySlackService.postMessage(
        channelId ?? slackChannel,
        fallbackText,
        blocks
    );

    if (!postResult.sent) {
        logger.error('[DailyBriefing] Failed to post', { orgId, error: postResult.error });
        return { success: false, artifactCount: allArtifacts.length, error: postResult.error };
    }

    // 6. Store Slack message TS on artifacts (for update-on-action)
    const channel = channelId ?? slackChannel;
    const updateBatch = db.batch();
    for (const artifact of allArtifacts) {
        if (artifact.actionable?.requiresApproval) {
            const ref = db
                .collection('tenants')
                .doc(orgId)
                .collection('inbox_artifacts')
                .doc(artifact.id);
            updateBatch.update(ref, {
                slackMessageTs: postResult.ts,
                slackChannel: channel,
            });
        }
    }
    await updateBatch.commit();

    logger.info('[DailyBriefing] Posted successfully', {
        orgId,
        artifactCount: allArtifacts.length,
        ts: postResult.ts,
    });

    return {
        success: true,
        artifactCount: allArtifacts.length,
        slackTs: postResult.ts,
    };
}

// ============================================================================
// Org Discovery
// ============================================================================

/**
 * Find all orgs with at least one active playbook.
 */
async function getOrgsWithActivePlaybooks(): Promise<string[]> {
    const db = getAdminFirestore();

    // Query tenants that have a slackChannel configured (proxy for "active pilot")
    const tenantsSnap = await db
        .collection('tenants')
        .where('slackChannel', '!=', null)
        .select('slackChannel')
        .limit(50)
        .get();

    return tenantsSnap.docs.map(doc => doc.id);
}
