import type { Product, Location } from './types';
import { PlaceHolderImages } from './placeholder-images';

// Direct export of default assets to prevent broken links.
export const defaultLogo = 'https://storage.googleapis.com/stedi-assets/misc/bakedbot-logo-horizontal.png';
export const defaultChatbotIcon = 'https://storage.googleapis.com/stedi-assets/misc/smokey-icon-1.png';


export const demoProducts: Product[] = [
    {
      id: '1',
      name: 'Cosmic Caramels',
      category: 'Edibles',
      price: 25.00,
      prices: { '1': 25.00, '2': 27.50, '3': 24.00 },
      imageUrl: PlaceHolderImages.find(p => p.id === 'product1')?.imageUrl || 'https://picsum.photos/seed/1/600/400',
      imageHint: PlaceHolderImages.find(p => p.id === 'product1')?.imageHint || 'cannabis edible',
      description: 'Chewy, rich caramels infused with full-spectrum cannabis oil. A perfect treat for a relaxing evening.',
      likes: 134,
      dislikes: 5,
    },
    {
      id: '2',
      name: 'Giggle Gummies',
      category: 'Edibles',
      price: 22.00,
      prices: { '1': 22.00, '2': 23.00, '3': 21.50 },
      imageUrl: PlaceHolderImages.find(p => p.id === 'product2')?.imageUrl || 'https://picsum.photos/seed/2/600/400',
      imageHint: PlaceHolderImages.find(p => p.id === 'product2')?.imageHint || 'cannabis gummy',
      description: 'Fruity, fun, and uplifting. These sativa-dominant gummies are great for social gatherings and creative boosts.',
      likes: 212,
      dislikes: 12,
    },
    {
      id: '3',
      name: 'Stardust Suckers',
      category: 'Edibles',
      price: 18.00,
      prices: { '1': 18.00, '2': 19.00, '3': 17.00 },
      imageUrl: PlaceHolderImages.find(p => p.id === 'product3')?.imageUrl || 'https://picsum.photos/seed/3/600/400',
      imageHint: PlaceHolderImages.find(p => p.id === 'product3')?.imageHint || 'cannabis candy',
      description: 'Long-lasting, flavorful lollipops with a balanced hybrid effect. Ideal for a steady, manageable high.',
      likes: 98,
      dislikes: 2,
    },
    {
      id: '4',
      name: 'OG Galaxy',
      category: 'Flower',
      price: 55.00,
      prices: { '1': 55.00, '2': 58.00, '3': 54.00 },
      imageUrl: PlaceHolderImages.find(p => p.id === 'product4')?.imageUrl || 'https://picsum.photos/seed/4/600/400',
      imageHint: PlaceHolderImages.find(p => p.id === 'product4')?.imageHint || 'cannabis flower',
      description: 'A classic indica-dominant strain known for its potent relaxing effects and earthy pine aroma. An eighth (3.5g).',
      likes: 450,
      dislikes: 25,
    },
    {
      id: '5',
      name: 'Nebula Nugs',
      category: 'Flower',
      price: 60.00,
      prices: { '1': 60.00, '2': 62.00, '3': 59.00 },
      imageUrl: PlaceHolderImages.find(p => p.id === 'product5')?.imageUrl || 'https://picsum.photos/seed/5/600/400',
      imageHint: PlaceHolderImages.find(p => p.id === 'product5')?.imageHint || 'cannabis nug',
      description: 'Dense, trichome-covered nugs with a sweet and pungent aroma. A premium flower for the discerning connoisseur. An eighth (3.5g).',
      likes: 510,
      dislikes: 15,
    },
    {
        id: '6',
        name: 'Supernova Haze',
        category: 'Flower',
        price: 58.00,
        prices: { '1': 58.00, '2': 60.00, '3': 57.50 },
        imageUrl: PlaceHolderImages.find(p => p.id === 'product6')?.imageUrl || 'https://picsum.photos/seed/6/600/400',
        imageHint: PlaceHolderImages.find(p => p.id === 'product6')?.imageHint || 'cannabis strain',
        description: 'A powerful sativa strain with citrus notes and an energetic, cerebral high. Perfect for daytime use. An eighth (3.5g).',
        likes: 380,
        dislikes: 18,
    },
    {
        id: '7',
        name: 'Vaporwave Voyage',
        category: 'Vapes',
        price: 45.00,
        prices: { '1': 45.00, '2': 48.00, '3': 44.00 },
        imageUrl: PlaceHolderImages.find(p => p.id === 'product7')?.imageUrl || 'https://picsum.photos/seed/7/600/400',
        imageHint: PlaceHolderImages.find(p => p.id === 'product7')?.imageHint || 'cannabis vape',
        description: 'A sleek, disposable vape pen with a balanced hybrid oil. Smooth, flavorful, and discreet. 1g cartridge.',
        likes: 280,
        dislikes: 8,
    },
    {
        id: '8',
        name: 'Comet Stick',
        category: 'Vapes',
        price: 42.00,
        prices: { '1': 42.00, '2': 45.00, '3': 40.00 },
        imageUrl: PlaceHolderImages.find(p => p.id === 'product8')?.imageUrl || 'https://picsum.photos/seed/8/600/400',
        imageHint: PlaceHolderImages.find(p => p.id === 'product8')?.imageHint || 'vape pen',
        description: 'An indica-dominant vape pen designed for relaxation and sleep. Natural berry flavors. 1g cartridge.',
        likes: 195,
        dislikes: 4,
    },
     {
        id: '9',
        name: 'Pulsar Pod',
        category: 'Vapes',
        price: 48.00,
        prices: { '1': 48.00, '2': 50.00, '3': 47.00 },
        imageUrl: PlaceHolderImages.find(p => p.id === 'product9')?.imageUrl || 'https://picsum.photos/seed/9/600/400',
        imageHint: PlaceHolderImages.find(p => p.id === 'product9')?.imageHint || 'vape cartridge',
        description: 'A high-potency sativa cartridge with a tangy citrus flavor. Expect an uplifting and creative experience. 1g cartridge.',
        likes: 320,
        dislikes: 10,
    }
  ];

export const demoLocations: Location[] = [
    {
        id: '1',
        name: 'The Green Spot',
        address: '123 Leafy Lane',
        city: 'Denver',
        state: 'CO',
        zip: '80202',
        phone: '303-123-4567',
        email: 'orders@thegreenspot.com',
        lat: 39.7392,
        lon: -104.9903,
    },
    {
        id: '2',
        name: 'High Altitude Herbs',
        address: '456 Mountain View',
        city: 'Boulder',
        state: 'CO',
        zip: '80302',
        phone: '303-987-6543',
        email: 'orders@highaltitudeherbs.com',
        lat: 40.0150,
        lon: -105.2705,
    },
    {
        id: '3',
        name: 'City Cannabis Collective',
        address: '789 Urban Avenue',
        city: 'Denver',
        state: 'CO',
        zip: '80204',
        phone: '720-555-1212',
        email: 'orders@citycannabisco.com',
        lat: 39.7420,
        lon: -104.9915,
    },
    {
        id: '4',
        name: 'Rocky Mountain Remedies',
        address: '101 Peak Place',
        city: 'Estes Park',
        state: 'CO',
        zip: '80517',
        phone: '970-555-8888',
        email: 'orders@rmremedies.com',
        lat: 40.3772,
        lon: -105.5217,
    }
];
