/**
 * Vibe Builder - Export API
 *
 * Exports project as downloadable ZIP file with HTML, CSS, and assets
 */

import { NextRequest, NextResponse } from 'next/server';
import { getVibeProject } from '@/server/actions/vibe-projects';
import JSZip from 'jszip';

export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const projectId = searchParams.get('projectId');

    if (!projectId) {
      return NextResponse.json(
        { error: 'Project ID is required' },
        { status: 400 }
      );
    }

    // Fetch project
    const project = await getVibeProject(projectId);

    if (!project) {
      return NextResponse.json(
        { error: 'Project not found' },
        { status: 404 }
      );
    }

    // Create ZIP file
    const zip = new JSZip();

    // Add index.html
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="${project.description || project.name}">
  <title>${project.name}</title>
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@3/dist/tailwind.min.css" rel="stylesheet">
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  ${project.html}

  <script src="script.js"></script>
</body>
</html>`;

    zip.file('index.html', html);

    // Add styles.css
    const css = `/* ${project.name} - Styles */
/* Generated by BakedBot Vibe Builder */

${project.css}

/* Additional custom styles */
* {
  box-sizing: border-box;
}

body {
  margin: 0;
  padding: 0;
}
`;

    zip.file('styles.css', css);

    // Add script.js with basic interactivity
    const script = `// ${project.name} - JavaScript
// Generated by BakedBot Vibe Builder

// Age gate functionality
document.addEventListener('DOMContentLoaded', function() {
  const ageGate = document.querySelector('[data-gjs-type="age-gate"]');

  if (ageGate) {
    const acceptButton = ageGate.querySelector('button:first-of-type');
    const exitButton = ageGate.querySelector('button:last-of-type');

    if (acceptButton) {
      acceptButton.addEventListener('click', function() {
        ageGate.style.display = 'none';
        localStorage.setItem('ageVerified', 'true');
      });
    }

    if (exitButton) {
      exitButton.addEventListener('click', function() {
        window.location.href = 'https://www.samhsa.gov/marijuana';
      });
    }

    // Check if already verified
    if (localStorage.getItem('ageVerified') === 'true') {
      ageGate.style.display = 'none';
    }
  }

  // Form submission handling
  const forms = document.querySelectorAll('form');
  forms.forEach(form => {
    form.addEventListener('submit', function(e) {
      e.preventDefault();
      alert('Form submitted! Connect this to your backend.');
    });
  });

  // Add to cart buttons
  const addToCartButtons = document.querySelectorAll('button');
  addToCartButtons.forEach(button => {
    if (button.textContent.includes('Add to Cart')) {
      button.addEventListener('click', function() {
        alert('Product added to cart! Connect this to your e-commerce system.');
      });
    }
  });
});
`;

    zip.file('script.js', script);

    // Add README
    const readme = `# ${project.name}

Created with BakedBot Vibe Builder

## Files Included

- **index.html** - Main HTML file
- **styles.css** - Custom styles (uses Tailwind CSS CDN)
- **script.js** - Basic JavaScript functionality
- **README.md** - This file

## Setup Instructions

1. Upload all files to your web hosting provider
2. Ensure index.html is in the root directory
3. Access your site at your domain

## Customization

### Connecting to Your POS
The product grid displays sample products. To connect to your POS:

1. Replace product data in index.html with your POS API
2. Add authentication if required
3. Update prices and availability in real-time

### Forms
Forms currently show alerts. To connect to your backend:

1. Add a form action URL
2. Set up server-side processing
3. Add email notifications or database storage

### E-Commerce
To enable actual checkout:

1. Integrate with Shopify, WooCommerce, or custom cart
2. Add payment processing (Stripe, Square, etc.)
3. Set up order management

## Deployment Options

### Option 1: BakedBot Hosting (Recommended)
- Return to Vibe Builder and click "Publish"
- Automatic deployment with SSL
- Custom domain support
- POS integration included

### Option 2: Manual Hosting
Upload to any web host:
- Netlify (drag & drop)
- Vercel (GitHub integration)
- Traditional hosting (FTP upload)

## Support

For questions or help:
- Visit: https://bakedbot.ai
- Email: support@bakedbot.ai
- Documentation: https://bakedbot.ai/help

Built with ❤️ using BakedBot Vibe Builder
`;

    zip.file('README.md', readme);

    // Generate ZIP buffer
    const zipBuffer = await zip.generateAsync({
      type: 'nodebuffer',
      compression: 'DEFLATE',
      compressionOptions: { level: 9 },
    });

    // Return ZIP file
    const fileName = `${project.name.toLowerCase().replace(/\s+/g, '-')}-export.zip`;

    // Convert Buffer to Uint8Array for NextResponse
    const uint8Array = new Uint8Array(zipBuffer);

    return new NextResponse(uint8Array, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${fileName}"`,
        'Content-Length': uint8Array.length.toString(),
      },
    });
  } catch (error) {
    console.error('[VIBE-EXPORT] Export failed:', error);
    return NextResponse.json(
      { error: 'Failed to export project' },
      { status: 500 }
    );
  }
}
