// Try to load env-config.json (generated by CI)
let ciEnv = {};
try {
  ciEnv = require('./env-config.json');
} catch (e) {
  // Ignore if not present (local dev)
}

/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    ...ciEnv,
  },
  output: 'standalone',
  reactStrictMode: true,

  // Build performance optimizations
  productionBrowserSourceMaps: false,  // Disable source maps - saves memory and time

  // Reduce compilation overhead
  images: {
    // Allow any external image URL — needed for brand logos from diverse brand websites
    remotePatterns: [
      { protocol: 'https', hostname: '**' },
      { protocol: 'http', hostname: '**' },
    ],
  },
  experimental: {
    optimizeServerReact: true,
    optimizePackageImports: ['lucide-react', 'framer-motion', '@radix-ui/react-icons', 'date-fns', 'recharts'],
  },
  serverExternalPackages: [
    // Remotion (video rendering — native deps)
    'remotion', '@remotion/renderer', '@remotion/bundler',
    // LanceDB (native bindings)
    '@lancedb/lancedb',
    '@lancedb/lancedb-darwin-arm64', '@lancedb/lancedb-linux-arm64-gnu',
    '@lancedb/lancedb-linux-arm64-musl', '@lancedb/lancedb-linux-x64-gnu',
    '@lancedb/lancedb-linux-x64-musl', '@lancedb/lancedb-win32-arm64-msvc',
    '@lancedb/lancedb-win32-x64-msvc',
    // LiveKit
    'livekit-server-sdk',
    // Genkit + OpenTelemetry
    'genkit', '@genkit-ai/google-genai', '@genkit-ai/vertexai', '@genkit-ai/core',
    '@opentelemetry/sdk-node', '@opentelemetry/instrumentation',
    // Google Cloud SDKs
    'google-auth-library',
    '@google-cloud/firestore', '@google-cloud/monitoring', '@google-cloud/secret-manager',
    '@google-cloud/logging', '@google-analytics/data',
    // Firebase + Google APIs
    'firebase-admin', 'googleapis',
    // AI SDKs
    '@anthropic-ai/sdk', 'openai', '@google/generative-ai',
    '@mendable/firecrawl-js', 'apify-client',
    // Communication
    'resend', '@sendgrid/mail', 'twilio', 'node-mailjet', '@aws-sdk/client-ses',
    // Payments
    'stripe', 'square', 'authorizenet',
    // Data/file processing
    'adm-zip', 'archiver', 'jszip', 'xlsx', 'papaparse',
    // Web3
    '@coinbase/coinbase-sdk', 'ccxt',
    // Utilities (large or native)
    'puppeteer-core', '@sparticuz/chromium', 'pptxgenjs', 'express',
    'web-push', 'qrcode', 'passkit-generator',
    // Integrations
    '@linear/sdk', '@notionhq/client', '@octokit/rest', '@slack/web-api',
    // Node built-ins (shouldn't need bundling)
    'fs', 'path', 'os',
  ],
  typescript: {
    // Disable Next.js TypeScript checking - we run tsc --noEmit separately in check:types
    // This avoids duplicate TS compilation and memory issues in Firebase builds
    ignoreBuildErrors: true,
  },
  // Include src/skills/ static files (SKILL.md, eval_spec.json, hard_rules.json, *.jsonl, metadata.json)
  // in the standalone build output so server actions can read them via fs at runtime.
  outputFileTracingIncludes: {
    '/': ['./src/skills/**/*', './.remotion/bundle/**/*'],
  },

  // Webpack memory optimization — serial compilation uses less peak memory.
  // Also explicitly externalize heavy packages from the server bundle.
  // This is a direct webpack-level guard: Firebase adapter v14.0.21 moves
  // serverExternalPackages → experimental.serverComponentsExternalPackages (invalid
  // in Next.js 16), so those packages get bundled. The externals function below
  // prevents that regardless of what the adapter does to the config.
  webpack: (config, { isServer, dev }) => {
    // Firebase App Hosting build containers have 6GB RAM.
    // Parallel webpack + Next.js bundling exhausts that budget and triggers OOM timeouts.
    // We throttle only in production builds (Firebase). Local dev uses full parallelism.
    if (!dev) {
      config.parallelism = 1;
    }
    // Remotion bundles reference zod/v3 which doesn't exist in zod@3.x
    // Alias to zod root to fix build errors
    config.resolve.alias = {
      ...config.resolve.alias,
      'zod/v3': 'zod',
    };
    if (isServer) {
      // Packages that must never be bundled by webpack (too large / native bindings).
      // Keep in sync with serverExternalPackages above.
      const SERVER_ONLY_EXTERNALS = [
        'remotion', '@remotion/renderer', '@remotion/bundler',
        '@lancedb/lancedb', 'livekit-server-sdk',
        'genkit', '@genkit-ai/google-genai', '@genkit-ai/vertexai', '@genkit-ai/core',
        '@opentelemetry/sdk-node', '@opentelemetry/instrumentation',
        'google-auth-library',
        '@google-cloud/firestore', '@google-cloud/monitoring', '@google-cloud/secret-manager',
        '@google-cloud/logging', '@google-analytics/data',
        'firebase-admin', 'googleapis',
        '@anthropic-ai/sdk', 'openai', '@google/generative-ai',
        '@mendable/firecrawl-js', 'apify-client',
        'resend', '@sendgrid/mail', 'twilio', 'node-mailjet', '@aws-sdk/client-ses',
        'stripe', 'square', 'authorizenet',
        'adm-zip', 'archiver', 'jszip', 'xlsx', 'papaparse',
        '@coinbase/coinbase-sdk', 'ccxt',
        'puppeteer-core', '@sparticuz/chromium', 'pptxgenjs', 'express',
        'web-push', 'qrcode', 'passkit-generator',
        '@linear/sdk', '@notionhq/client', '@octokit/rest', '@slack/web-api',
      ];
      const existingExternals = config.externals || [];
      config.externals = [
        ...(Array.isArray(existingExternals) ? existingExternals : [existingExternals]),
        ({ request }, callback) => {
          const pkg = SERVER_ONLY_EXTERNALS.find(
            (p) => request === p || request.startsWith(p + '/') || request.startsWith(p + '\\')
          );
          if (pkg) return callback(null, 'commonjs ' + request);
          callback();
        },
      ];
    }
    return config;
  },

  async headers() {
    const isProd = process.env.NODE_ENV === 'production';

    return [
      // Service worker must not be cached for reliable updates
      {
        source: '/sw.js',
        headers: [
          {
            key: 'Cache-Control',
            value: 'no-cache, no-store, must-revalidate',
          },
          {
            key: 'Service-Worker-Allowed',
            value: '/',
          },
        ],
      },
      // Embed routes - allow iframe embedding from any origin
      {
        source: '/embed/:path*',
        headers: [
          {
            key: 'X-Frame-Options',
            value: 'ALLOWALL',
          },
          {
            key: 'Content-Security-Policy',
            value: "frame-ancestors *",
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff',
          },
        ],
      },
      // Security headers for all routes
      {
        source: '/(.*)',
        headers: [
          // NOTE: Cross-Origin-Opener-Policy removed to fix Firebase OAuth popup flow
          // Even 'same-origin-allow-popups' can cause issues with some browsers
          {
            key: 'X-Frame-Options',
            value: 'DENY',
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff',
          },
          {
            key: 'Referrer-Policy',
            value: 'strict-origin-when-cross-origin',
          },
          {
            key: 'Permissions-Policy',
            value: 'camera=(), microphone=(), geolocation=(self)',
          },
          {
            key: 'X-XSS-Protection',
            value: '1; mode=block',
          },
        ],
      },
      // CSP for pages (strict)
      {
        source: '/((?!api/).*)',
        headers: [
          {
            key: 'Content-Security-Policy',
            value: isProd
              ? [
                "default-src 'self'",
                "script-src 'self' 'unsafe-eval' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://cdn.jsdelivr.net https://apis.google.com https://accounts.google.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/",
                "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
                "img-src 'self' data: https: blob:",
                "media-src 'self' data: https: blob: https://storage.googleapis.com https://commondatastorage.googleapis.com",
                "font-src 'self' data: https://fonts.gstatic.com",
                "connect-src 'self' https://*.googleapis.com https://apis.google.com https://*.firebaseio.com wss://*.firebaseio.com https://api.cannmenus.com https://api.anthropic.com https://www.google.com/recaptcha/ https://accounts.google.com https://www.google-analytics.com https://www.googletagmanager.com https://analytics.google.com https://nominatim.openstreetmap.org wss://*.livekit.cloud https://*.livekit.cloud https://singleview.site",
                "frame-src 'self' https://www.google.com https://accounts.google.com https://www.google.com/recaptcha/ https://recaptcha.google.com/recaptcha/ https://studio-567050101-bc6e8.firebaseapp.com",
                "object-src 'none'",
                "base-uri 'self'",
                "form-action 'self'",
                "frame-ancestors 'self'",
                "upgrade-insecure-requests",
              ].join('; ')
              : "default-src 'self' 'unsafe-eval' 'unsafe-inline'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://apis.google.com https://www.googletagmanager.com; img-src 'self' data: https: blob:; connect-src 'self' http://localhost:* ws://localhost:* https:;",
          },
        ],
      },
      // CORS headers for API routes
      // Note: For proper CORS with credentials, we handle origin dynamically in middleware
      // Static headers set baseline security, actual origin validation in API routes
      {
        source: '/api/:path*',
        headers: [
          {
            key: 'Access-Control-Allow-Methods',
            value: 'GET,POST,PUT,DELETE,OPTIONS',
          },
          {
            key: 'Access-Control-Allow-Headers',
            value: 'X-Requested-With, Content-Type, Authorization, X-Firebase-AppCheck',
          },
          {
            key: 'Access-Control-Max-Age',
            value: '86400',
          },
        ],
      },
    ];
  },
  async redirects() {
    return [
      {
        source: '/pricing',
        has: [{ type: 'query', key: 'plan', value: 'empire' }],
        destination: '/pricing/launch',
        permanent: true,
      },
      {
        source: '/checkout/subscription',
        has: [{ type: 'query', key: 'plan', value: 'pro' }],
        destination: '/pricing/launch',
        permanent: true,
      },
      {
        source: '/checkout/subscription',
        has: [{ type: 'query', key: 'plan', value: 'growth' }],
        destination: '/pricing/launch',
        permanent: true,
      },
      {
        source: '/checkout/subscription',
        has: [{ type: 'query', key: 'plan', value: 'scout' }],
        destination: '/pricing/launch',
        permanent: true,
      },
      {
        source: '/executive/:id',
        destination: '/demo-shop',
        permanent: true,
      },
      {
        source: '/demo-menu',
        destination: '/demo-shop',
        permanent: true,
      },
      {
        source: '/shop/demo',
        destination: '/demo-shop',
        permanent: true,
      },
      {
        source: '/demo',
        destination: '/demo-shop',
        permanent: true,
      },
      // Executive short booking URLs — bakedbot.ai/martez and bakedbot.ai/jack
      {
        source: '/martez',
        destination: '/book/martez',
        permanent: false,
      },
      {
        source: '/jack',
        destination: '/book/jack',
        permanent: false,
      },
    ];
  },
  async rewrites() {
    // Andrews Developments WordPress site proxied from Cloud Run
    // Use beforeFiles so this takes priority over the [brand] dynamic route
    const andrewsWpUrl = process.env.ANDREWS_WP_URL || 'https://andrews-wp-lo74oftdza-uc.a.run.app';
    return {
      beforeFiles: [
        {
          source: '/andrewsdevelopments',
          destination: `${andrewsWpUrl}/`,
        },
        {
          source: '/andrewsdevelopments/:path*',
          destination: `${andrewsWpUrl}/:path*`,
        },
      ],
    };
  },
};
// Cache invalidate: webpack externals guard for Firebase adapter. 2026-04-01 10:15:00
module.exports = nextConfig;
