// Try to load env-config.json (generated by CI)
let ciEnv = {};
try {
  ciEnv = require('./env-config.json');
} catch (e) {
  // Ignore if not present (local dev)
}

/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    ...ciEnv,
  },
  output: 'standalone',
  reactStrictMode: true,

  // Build performance optimizations
  productionBrowserSourceMaps: false,  // Disable source maps - saves memory and time

  // Reduce compilation overhead
  images: {
    // Allow any external image URL — needed for brand logos from diverse brand websites
    remotePatterns: [
      { protocol: 'https', hostname: '**' },
      { protocol: 'http', hostname: '**' },
    ],
  },
  serverExternalPackages: [
    'livekit-server-sdk',
    'genkit',
    '@genkit-ai/google-genai',
    '@genkit-ai/vertexai',
    '@genkit-ai/core',
    '@opentelemetry/sdk-node',
    '@opentelemetry/instrumentation',
    'google-auth-library',
    '@google-cloud/monitoring',
    'firebase-admin',
    'googleapis',
    'resend',
    'stripe',
    'twilio',
    'adm-zip',
    'archiver',
    'jszip',
    'xlsx',
    'fs',
    'path',
    'os',
  ],
  typescript: {
    // Disable Next.js TypeScript checking - we run tsc --noEmit separately in check:types
    // This avoids duplicate TS compilation and memory issues in Firebase builds
    ignoreBuildErrors: true,
  },
  experimental: {
    // Reduce webpack memory usage during builds (helps avoid OOM on Firebase App Hosting)
    webpackMemoryOptimizations: true,
    // Reduce concurrent page compilations to prevent memory spikes
    workerThreads: false,
    cpus: 1,
    // Optimize CSS handling
    optimizeCss: false,  // Skip CSS optimization to save memory
    // Improve build performance
    optimizeServerReact: true,  // Optimize React server components
    optimizePackageImports: [
      'lucide-react',
      'framer-motion',
      '@radix-ui/react-icons',
      'date-fns',
      'recharts',
    ],
  },

  // Turbopack configuration (silence Next.js 16 default Turbopack warning when webpack config is present)
  turbopack: {},

  // Webpack configuration for aggressive memory optimization (when not using Turbopack)
  webpack: (config, { isServer }) => {
    // Aggressive code splitting to reduce chunk sizes and memory usage during compilation
    if (!isServer) {
      config.optimization = {
        ...config.optimization,
        splitChunks: {
          chunks: 'all',
          cacheGroups: {
            default: false,
            vendors: false,
            // Split large dependencies into separate chunks to reduce per-chunk compilation memory
            framework: {
              name: 'framework',
              test: /[\\/]node_modules[\\/](react|react-dom|scheduler|next)[\\/]/,
              priority: 40,
              enforce: true,
            },
            firebase: {
              name: 'firebase',
              test: /[\\/]node_modules[\\/](firebase|@google-cloud|@firebase|googleapis)[\\/]/,
              priority: 30,
              enforce: true,
            },
            ui: {
              name: 'ui',
              test: /[\\/]node_modules[\\/](@radix-ui|@tanstack|framer-motion|lucide-react)[\\/]/,
              priority: 25,
              enforce: true,
            },
            lib: {
              test: /[\\/]node_modules[\\/]/,
              name(module) {
                const packageName = module.context.match(/[\\/]node_modules[\\/](.*?)([\\/]|$)/)?.[1];
                return `npm.${packageName?.replace('@', '')}`;
              },
              priority: 20,
              minSize: 50000,
            },
          },
          // Limit chunk sizes to prevent memory spikes during compilation
          maxSize: 400000,
        },
        // Disable module concatenation - saves memory during build
        concatenateModules: false,
      };
    }

    // CRITICAL: Reduce parallelism to 1 to prevent memory spikes
    // With 204 pages, parallel compilation causes OOM
    config.parallelism = 1;

    // Disable filesystem cache to save memory at the cost of build time
    config.cache = false;

    return config;
  },

  async headers() {
    const isProd = process.env.NODE_ENV === 'production';

    return [
      // Service worker must not be cached for reliable updates
      {
        source: '/sw.js',
        headers: [
          {
            key: 'Cache-Control',
            value: 'no-cache, no-store, must-revalidate',
          },
          {
            key: 'Service-Worker-Allowed',
            value: '/',
          },
        ],
      },
      // Embed routes - allow iframe embedding from any origin
      {
        source: '/embed/:path*',
        headers: [
          {
            key: 'X-Frame-Options',
            value: 'ALLOWALL',
          },
          {
            key: 'Content-Security-Policy',
            value: "frame-ancestors *",
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff',
          },
        ],
      },
      // Security headers for all routes
      {
        source: '/(.*)',
        headers: [
          // NOTE: Cross-Origin-Opener-Policy removed to fix Firebase OAuth popup flow
          // Even 'same-origin-allow-popups' can cause issues with some browsers
          {
            key: 'X-Frame-Options',
            value: 'DENY',
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff',
          },
          {
            key: 'Referrer-Policy',
            value: 'strict-origin-when-cross-origin',
          },
          {
            key: 'Permissions-Policy',
            value: 'camera=(), microphone=(), geolocation=(self)',
          },
          {
            key: 'X-XSS-Protection',
            value: '1; mode=block',
          },
        ],
      },
      // CSP for pages (strict)
      {
        source: '/((?!api/).*)',
        headers: [
          {
            key: 'Content-Security-Policy',
            value: isProd
              ? [
                "default-src 'self'",
                "script-src 'self' 'unsafe-eval' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://cdn.jsdelivr.net https://apis.google.com https://accounts.google.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/",
                "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
                "img-src 'self' data: https: blob:",
                "media-src 'self' data: https: blob: https://storage.googleapis.com https://commondatastorage.googleapis.com",
                "font-src 'self' data: https://fonts.gstatic.com",
                "connect-src 'self' https://*.googleapis.com https://apis.google.com https://*.firebaseio.com wss://*.firebaseio.com https://api.cannmenus.com https://api.anthropic.com https://www.google.com/recaptcha/ https://accounts.google.com https://www.google-analytics.com https://www.googletagmanager.com https://analytics.google.com https://nominatim.openstreetmap.org wss://*.livekit.cloud https://*.livekit.cloud",
                "frame-src 'self' https://www.google.com https://accounts.google.com https://www.google.com/recaptcha/ https://recaptcha.google.com/recaptcha/ https://studio-567050101-bc6e8.firebaseapp.com",
                "object-src 'none'",
                "base-uri 'self'",
                "form-action 'self'",
                "frame-ancestors 'self'",
                "upgrade-insecure-requests",
              ].join('; ')
              : "default-src 'self' 'unsafe-eval' 'unsafe-inline'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://apis.google.com https://www.googletagmanager.com; img-src 'self' data: https: blob:; connect-src 'self' http://localhost:* ws://localhost:* https:;",
          },
        ],
      },
      // CORS headers for API routes
      // Note: For proper CORS with credentials, we handle origin dynamically in middleware
      // Static headers set baseline security, actual origin validation in API routes
      {
        source: '/api/:path*',
        headers: [
          {
            key: 'Access-Control-Allow-Methods',
            value: 'GET,POST,PUT,DELETE,OPTIONS',
          },
          {
            key: 'Access-Control-Allow-Headers',
            value: 'X-Requested-With, Content-Type, Authorization, X-Firebase-AppCheck',
          },
          {
            key: 'Access-Control-Max-Age',
            value: '86400',
          },
        ],
      },
    ];
  },
  async redirects() {
    return [
      {
        source: '/demo-menu',
        destination: '/demo-shop',
        permanent: true,
      },
      {
        source: '/shop/demo',
        destination: '/demo-shop',
        permanent: true,
      },
      {
        source: '/demo',
        destination: '/demo-shop',
        permanent: true,
      },
      // Executive short booking URLs — bakedbot.ai/martez and bakedbot.ai/jack
      {
        source: '/martez',
        destination: '/book/martez',
        permanent: false,
      },
      {
        source: '/jack',
        destination: '/book/jack',
        permanent: false,
      },
    ];
  },
};
// Cache invalidate: Force rebuild for new secret v7. 2025-12-04 14:51:51
module.exports = nextConfig;
