steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.andrews'
      - '-t'
      - 'us-central1-docker.pkg.dev/studio-567050101-bc6e8/andrews-wp/andrews-wp:latest'
      - '.'

images:
  - 'us-central1-docker.pkg.dev/studio-567050101-bc6e8/andrews-wp/andrews-wp:latest'

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
