'use client';

import { useState, useEffect, useTransition, type ElementType } from 'react';
import { useUserRole } from '@/hooks/use-user-role';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import {
    MessageSquare, Building2, User, Megaphone, Key,
    Copy, Check, Loader2, ChevronLeft,
} from 'lucide-react';
import Link from 'next/link';
import {
    getSmsRegistration,
    saveSmsRegistration,
    emailSmsRegistration,
} from '@/server/actions/sms-registration';
import {
    EMPTY_SMS_REGISTRATION,
    type SmsRegistrationData,
} from '@/server/actions/sms-registration-types';

// ---------------------------------------------------------------------------
// Layout helpers
// ---------------------------------------------------------------------------

function Section({ icon: Icon, title, description, children }: {
    icon: ElementType;
    title: string;
    description: string;
    children: React.ReactNode;
}) {
    return (
        <Card>
            <CardHeader>
                <CardTitle className="flex items-center gap-2 text-base">
                    <Icon className="h-4 w-4 text-primary" />
                    {title}
                </CardTitle>
                <CardDescription>{description}</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">{children}</CardContent>
        </Card>
    );
}

function Row({ children }: { children: React.ReactNode }) {
    return <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{children}</div>;
}

function Field({ label, required, children }: { label: string; required?: boolean; children: React.ReactNode }) {
    return (
        <div className="space-y-1.5">
            <Label className="text-sm">
                {label}{required && <span className="text-destructive ml-0.5">*</span>}
            </Label>
            {children}
        </div>
    );
}

// ---------------------------------------------------------------------------
// Copy-all export
// ---------------------------------------------------------------------------

function buildExportText(d: SmsRegistrationData): string {
    return `SMS / 10DLC BRAND REGISTRATION — ${d.legalName}
Generated by BakedBot

BUSINESS INFORMATION
Legal Name: ${d.legalName}
DBA: ${d.dba || 'N/A'}
EIN: ${d.ein}
Entity Type: ${d.entityType}
Address: ${d.street}, ${d.city}, ${d.state} ${d.zip}
Website: ${d.website}
Years in Business: ${d.yearsInBusiness}
Industry: Cannabis Dispensary

AUTHORIZED CONTACT
Name: ${d.contactFirstName} ${d.contactLastName}
Title: ${d.contactTitle}
Email: ${d.contactEmail}
Phone: ${d.contactPhone}

CAMPAIGN REGISTRATION
Use Case: ${d.useCase}
Campaign Name: ${d.campaignName}
Description: ${d.campaignDescription}

Sample Messages:
1. ${d.sampleMessage1}
2. ${d.sampleMessage2}
${d.sampleMessage3 ? `3. ${d.sampleMessage3}` : ''}

Opt-in Method: ${d.optInMethod}
Opt-in Confirmation Text: ${d.optInConfirmation ? 'Yes' : 'No'}
Age Gate (21+): ${d.ageGate ? 'Yes' : 'No'}

SMS PROVIDER SETUP
Account Email: ${d.providerAccountEmail}
Preferred Area Code: ${d.preferredAreaCode || 'Any'}
API Key (post-registration): ${d.providerApiKey || '(pending)'}
`;
}

function getErrorMessage(error: unknown, fallback: string): string {
    if (error instanceof Error && error.message) {
        return error.message;
    }

    if (typeof error === 'string' && error.trim()) {
        return error;
    }

    return fallback;
}

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

export default function SmsRegistrationPage() {
    const { orgId } = useUserRole();
    const [data, setData] = useState<SmsRegistrationData>({ ...EMPTY_SMS_REGISTRATION });
    const [loading, setLoading] = useState(true);
    const [activeAction, setActiveAction] = useState<'draft' | 'submit' | null>(null);
    const [saved, setSaved] = useState(false);
    const [copied, setCopied] = useState(false);
    const [errorMessage, setErrorMessage] = useState<string | null>(null);
    const [, startTransition] = useTransition();
    const saving = activeAction !== null;

    useEffect(() => {
        if (!orgId) return;
        setLoading(true);
        setErrorMessage(null);
        getSmsRegistration(orgId)
            .then((reg) => {
                setData(reg);
            })
            .catch((error: unknown) => {
                setErrorMessage(getErrorMessage(error, 'Unable to load your SMS registration.'));
            })
            .finally(() => {
                setLoading(false);
            });
    }, [orgId]);

    function set<K extends keyof SmsRegistrationData>(key: K, value: SmsRegistrationData[K]) {
        setData((prev) => ({ ...prev, [key]: value }));
        setSaved(false);
        setErrorMessage(null);
    }

    function saveDraft() {
        if (!orgId) return;
        setActiveAction('draft');
        setErrorMessage(null);
        startTransition(async () => {
            try {
                const result = await saveSmsRegistration(orgId, { ...data, status: 'draft' });
                if (!result.success) {
                    setErrorMessage(result.error ?? 'Unable to save draft.');
                    return;
                }

                setData((prev) => ({ ...prev, status: 'draft' }));
                setSaved(true);
                setTimeout(() => setSaved(false), 3000);
            } catch (error: unknown) {
                setErrorMessage(getErrorMessage(error, 'Unable to save draft.'));
            } finally {
                setActiveAction(null);
            }
        });
    }

    function submitReady() {
        if (!orgId) return;
        setActiveAction('submit');
        setErrorMessage(null);
        startTransition(async () => {
            try {
                const readyRegistration = { ...data, status: 'ready' as const };
                const saveReadyResult = await saveSmsRegistration(orgId, readyRegistration);
                if (!saveReadyResult.success) {
                    setErrorMessage(saveReadyResult.error ?? 'Unable to save registration.');
                    return;
                }

                const emailResult = await emailSmsRegistration(orgId, readyRegistration);
                if (!emailResult.success) {
                    setData(readyRegistration);
                    setErrorMessage(emailResult.error ?? 'Registration saved, but email delivery failed.');
                    return;
                }

                const submittedRegistration = {
                    ...readyRegistration,
                    status: 'submitted' as const,
                };
                const saveSubmittedResult = await saveSmsRegistration(orgId, submittedRegistration);
                if (!saveSubmittedResult.success) {
                    setData(readyRegistration);
                    setErrorMessage(saveSubmittedResult.error ?? 'Registration sent, but submit state could not be saved.');
                    return;
                }

                setData(submittedRegistration);
                setSaved(true);
                setTimeout(() => setSaved(false), 3000);
            } catch (error: unknown) {
                setErrorMessage(getErrorMessage(error, 'Unable to submit registration.'));
            } finally {
                setActiveAction(null);
            }
        });
    }

    function copyToClipboard() {
        navigator.clipboard.writeText(buildExportText(data)).then(() => {
            setCopied(true);
            setTimeout(() => setCopied(false), 2500);
        });
    }

    const isReady = Boolean(
        data.legalName && data.ein && data.street && data.city && data.state && data.zip &&
        data.contactFirstName && data.contactEmail &&
        data.campaignDescription && data.sampleMessage1 && data.sampleMessage2 &&
        data.optInMethod && data.providerAccountEmail,
    );

    if (loading) {
        return (
            <div className="max-w-3xl mx-auto py-8 px-4 space-y-4">
                {[1, 2, 3].map((i) => (
                    <Card key={i}><CardContent className="h-32 animate-pulse bg-muted/40 rounded" /></Card>
                ))}
            </div>
        );
    }

    return (
        <div className="max-w-3xl mx-auto py-8 px-4 space-y-6">
            {/* Header */}
            <div className="flex items-start justify-between gap-4">
                <div>
                    <Button asChild variant="ghost" size="sm" className="mb-2 -ml-2 text-muted-foreground">
                        <Link href="/dashboard/settings?tab=sms"><ChevronLeft className="h-4 w-4 mr-1" />Settings</Link>
                    </Button>
                    <h1 className="text-2xl font-bold tracking-tight">SMS / 10DLC Registration</h1>
                    <p className="text-sm text-muted-foreground mt-1">
                        Brand and campaign data for 10DLC registration. Fill in all fields and submit it to the BakedBot team for review.
                    </p>
                </div>
                <Badge variant={data.status === 'submitted' ? 'default' : data.status === 'ready' ? 'secondary' : 'outline'}>
                    {data.status === 'draft' ? 'Draft' : data.status === 'ready' ? 'Ready' : 'Submitted'}
                </Badge>
            </div>

            {/* Section 1: Business */}
            <Section icon={Building2} title="Business Information" description="Legal entity details required for brand registration with The Campaign Registry (TCR).">
                <Row>
                    <Field label="Legal Business Name" required>
                        <Input value={data.legalName} onChange={(e) => set('legalName', e.target.value)} placeholder="Thrive Syracuse LLC" />
                    </Field>
                    <Field label="Doing Business As (DBA)">
                        <Input value={data.dba} onChange={(e) => set('dba', e.target.value)} placeholder="Thrive Syracuse" />
                    </Field>
                </Row>
                <Row>
                    <Field label="EIN / Tax ID" required>
                        <Input value={data.ein} onChange={(e) => set('ein', e.target.value)} placeholder="12-3456789" />
                    </Field>
                    <Field label="Entity Type" required>
                        <Select value={data.entityType} onValueChange={(v) => set('entityType', v)}>
                            <SelectTrigger><SelectValue /></SelectTrigger>
                            <SelectContent>
                                {['LLC', 'Corporation', 'S-Corporation', 'Sole Proprietor', 'Nonprofit', 'Partnership'].map((t) => (
                                    <SelectItem key={t} value={t}>{t}</SelectItem>
                                ))}
                            </SelectContent>
                        </Select>
                    </Field>
                </Row>
                <Field label="Street Address" required>
                    <Input value={data.street} onChange={(e) => set('street', e.target.value)} placeholder="123 Main St" />
                </Field>
                <Row>
                    <Field label="City" required>
                        <Input value={data.city} onChange={(e) => set('city', e.target.value)} placeholder="Syracuse" />
                    </Field>
                    <Field label="State" required>
                        <Input value={data.state} onChange={(e) => set('state', e.target.value)} placeholder="NY" maxLength={2} />
                    </Field>
                </Row>
                <Row>
                    <Field label="ZIP Code" required>
                        <Input value={data.zip} onChange={(e) => set('zip', e.target.value)} placeholder="13201" />
                    </Field>
                    <Field label="Years in Business">
                        <Input value={data.yearsInBusiness} onChange={(e) => set('yearsInBusiness', e.target.value)} placeholder="3" />
                    </Field>
                </Row>
                <Field label="Business Website" required>
                    <Input value={data.website} onChange={(e) => set('website', e.target.value)} placeholder="https://thrivesyracuse.com" />
                </Field>
            </Section>

            {/* Section 2: Contact */}
            <Section icon={User} title="Authorized Contact" description="The person responsible for this SMS account — must be authorized to act on behalf of the business.">
                <Row>
                    <Field label="First Name" required>
                        <Input value={data.contactFirstName} onChange={(e) => set('contactFirstName', e.target.value)} placeholder="Jane" />
                    </Field>
                    <Field label="Last Name" required>
                        <Input value={data.contactLastName} onChange={(e) => set('contactLastName', e.target.value)} placeholder="Doe" />
                    </Field>
                </Row>
                <Row>
                    <Field label="Title / Role">
                        <Input value={data.contactTitle} onChange={(e) => set('contactTitle', e.target.value)} placeholder="Owner" />
                    </Field>
                    <Field label="Contact Phone" required>
                        <Input value={data.contactPhone} onChange={(e) => set('contactPhone', e.target.value)} placeholder="(315) 555-0100" />
                    </Field>
                </Row>
                <Field label="Contact Email" required>
                    <Input type="email" value={data.contactEmail} onChange={(e) => set('contactEmail', e.target.value)} placeholder="jane@thrivesyracuse.com" />
                </Field>
            </Section>

            {/* Section 3: Campaign */}
            <Section icon={Megaphone} title="Campaign Registration" description="Describes how and why you'll send SMS. TCR reviews this alongside your brand registration.">
                <Row>
                    <Field label="Use Case" required>
                        <Select value={data.useCase} onValueChange={(v) => set('useCase', v)}>
                            <SelectTrigger><SelectValue /></SelectTrigger>
                            <SelectContent>
                                {['Marketing', 'Transactional', 'Mixed'].map((u) => (
                                    <SelectItem key={u} value={u}>{u}</SelectItem>
                                ))}
                            </SelectContent>
                        </Select>
                    </Field>
                    <Field label="Campaign Name" required>
                        <Input value={data.campaignName} onChange={(e) => set('campaignName', e.target.value)} placeholder="Thrive Customer Alerts" />
                    </Field>
                </Row>
                <Field label="Campaign Description" required>
                    <Textarea
                        value={data.campaignDescription}
                        onChange={(e) => set('campaignDescription', e.target.value)}
                        placeholder="Thrive Syracuse sends promotional offers, new product alerts, and order status updates to opted-in adult customers (21+) of our cannabis dispensary."
                        rows={3}
                    />
                </Field>

                <Separator />

                <p className="text-xs text-muted-foreground font-medium uppercase tracking-wide">Sample Messages (minimum 2 required)</p>
                <Field label="Sample Message 1" required>
                    <Textarea
                        value={data.sampleMessage1}
                        onChange={(e) => set('sampleMessage1', e.target.value)}
                        placeholder="Thrive Syracuse: Happy Hour deals are LIVE — 20% off all flower until 7PM. Must be 21+. Reply STOP to opt out."
                        rows={2}
                    />
                </Field>
                <Field label="Sample Message 2" required>
                    <Textarea
                        value={data.sampleMessage2}
                        onChange={(e) => set('sampleMessage2', e.target.value)}
                        placeholder="Your Thrive order #ABC123 is ready for pickup! Bring valid ID. Questions? Call (315) 555-0100. Reply STOP to opt out."
                        rows={2}
                    />
                </Field>
                <Field label="Sample Message 3 (optional)">
                    <Textarea
                        value={data.sampleMessage3}
                        onChange={(e) => set('sampleMessage3', e.target.value)}
                        placeholder="Thrive member exclusive: Double points this weekend on all edibles. Must be 21+. Reply STOP to opt out."
                        rows={2}
                    />
                </Field>

                <Separator />

                <Field label="Opt-in Method" required>
                    <Textarea
                        value={data.optInMethod}
                        onChange={(e) => set('optInMethod', e.target.value)}
                        placeholder="Customers opt in by providing their phone number at point of sale and checking a consent box on our website. Age (21+) is verified at purchase."
                        rows={2}
                    />
                </Field>
                <div className="flex flex-col sm:flex-row gap-6 pt-1">
                    <label className="flex items-center gap-3 cursor-pointer">
                        <Switch checked={data.optInConfirmation} onCheckedChange={(v) => set('optInConfirmation', v)} />
                        <span className="text-sm">Send opt-in confirmation text</span>
                    </label>
                    <label className="flex items-center gap-3 cursor-pointer">
                        <Switch checked={data.ageGate} onCheckedChange={(v) => set('ageGate', v)} />
                        <span className="text-sm">21+ age gate required</span>
                    </label>
                </div>
            </Section>

            {/* Section 4: Provider */}
            <Section icon={Key} title="SMS Provider Setup" description="Account details for your SMS provider. Add the API key here once registration is complete.">
                <Row>
                    <Field label="Provider Account Email" required>
                        <Input type="email" value={data.providerAccountEmail} onChange={(e) => set('providerAccountEmail', e.target.value)} placeholder="jane@thrivesyracuse.com" />
                    </Field>
                    <Field label="Preferred Area Code">
                        <Input value={data.preferredAreaCode} onChange={(e) => set('preferredAreaCode', e.target.value)} placeholder="315" maxLength={3} />
                    </Field>
                </Row>
                <Field label="API Key (fill after registration)">
                    <Input value={data.providerApiKey} onChange={(e) => set('providerApiKey', e.target.value)} placeholder="api_live_..." />
                </Field>
            </Section>

            {/* Actions */}
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pt-2">
                <div className="flex gap-2 flex-wrap">
                    <Button variant="outline" onClick={copyToClipboard} className="gap-2" disabled={!data.legalName}>
                        {copied ? <Check className="h-4 w-4 text-emerald-500" /> : <Copy className="h-4 w-4" />}
                        {copied ? 'Copied!' : 'Copy All'}
                    </Button>
                    <Button variant="outline" onClick={saveDraft} disabled={saving}>
                        {activeAction === 'draft' ? <Loader2 className="h-4 w-4 animate-spin mr-1" /> : null}
                        Save Draft
                    </Button>
                </div>
                <div className="flex items-center gap-3 flex-wrap">
                    {saved && <span className="text-xs text-emerald-600 flex items-center gap-1"><Check className="h-3.5 w-3.5" />Saved</span>}
                    <Button onClick={submitReady} disabled={!isReady || saving} className="gap-2">
                        {activeAction === 'submit' ? <Loader2 className="h-4 w-4 animate-spin" /> : <MessageSquare className="h-4 w-4" />}
                        Submit Registration
                    </Button>
                </div>
            </div>

            {errorMessage && (
                <p className="text-xs text-destructive">{errorMessage}</p>
            )}

            {!isReady && (
                <p className="text-xs text-muted-foreground">
                    Fill in all required fields <span className="text-destructive">*</span> to submit.
                </p>
            )}
        </div>
    );
}
