#!/bin/bash
# Setup CRON_SECRET for GitHub Actions and Firebase
# Run this script to generate a secure secret and get setup instructions

set -e

# Generate a secure random secret (32 bytes = 64 hex chars)
SECRET=$(openssl rand -hex 32)

echo "================================================"
echo "🔐 CRON_SECRET Setup Instructions"
echo "================================================"
echo ""
echo "Generated secure secret:"
echo ""
echo "  $SECRET"
echo ""
echo "================================================"
echo "📋 Step 1: Add to GitHub Actions"
echo "================================================"
echo ""
echo "1. Go to: https://github.com/admin-baked/bakedbot-for-brands/settings/secrets/actions"
echo "2. Click 'New repository secret'"
echo "3. Name: CRON_SECRET"
echo "4. Value: $SECRET"
echo "5. Click 'Add secret'"
echo ""
echo "================================================"
echo "📋 Step 2: Add to Firebase Secret Manager"
echo "================================================"
echo ""
echo "Run this command (requires gcloud auth):"
echo ""
echo "  echo '$SECRET' | gcloud secrets create CRON_SECRET \\"
echo "    --project=studio-567050101-bc6e8 \\"
echo "    --data-file=-"
echo ""
echo "Or if secret already exists, update it:"
echo ""
echo "  echo '$SECRET' | gcloud secrets versions add CRON_SECRET \\"
echo "    --project=studio-567050101-bc6e8 \\"
echo "    --data-file=-"
echo ""
echo "================================================"
echo "📋 Step 3: Grant Access to App Hosting"
echo "================================================"
echo ""
echo "Run this command:"
echo ""
echo "  firebase apphosting:secrets:grantaccess CRON_SECRET \\"
echo "    --project=studio-567050101-bc6e8"
echo ""
echo "================================================"
echo "✅ Step 4: Verify Setup"
echo "================================================"
echo ""
echo "Test the endpoint manually:"
echo ""
echo "  curl -X GET https://bakedbot.ai/api/cron/dayday-discovery \\"
echo "    -H 'Authorization: Bearer $SECRET'"
echo ""
echo "You should see:"
echo "  {\"success\": true, \"result\": {...}}"
echo ""
echo "================================================"
echo ""
echo "⚠️  IMPORTANT: Keep this secret secure!"
echo "    Do not commit it to git or share publicly."
echo ""
