
import type { Product, Retailer, Review, UserInteraction, OrderDoc, Location } from '@/types/domain';
import { PlaceHolderImages } from '@/lib/placeholder-images';
import { Timestamp } from 'firebase/firestore';


export const demoProducts: Product[] = [
    {
      id: '1',
      name: 'Cosmic Caramels',
      category: 'Edibles',
      price: 25.00,
      prices: { '1': 25.00, '2': 27.50, '3': 24.00 },
      imageUrl: PlaceHolderImages.find(p => p.id === 'product1')?.imageUrl || '',
      imageHint: PlaceHolderImages.find(p => p.id === 'product1')?.imageHint || '',
      description: 'Chewy, rich caramels infused with full-spectrum cannabis oil. A perfect treat for a relaxing evening.',
      likes: 134,
      dislikes: 5,
      brandId: 'default',
    },
    {
      id: '2',
      name: 'Giggle Gummies',
      category: 'Edibles',
      price: 22.00,
      prices: { '1': 22.00, '2': 23.00, '3': 21.50 },
      imageUrl: PlaceHolderImages.find(p => p.id === 'product2')?.imageUrl || '',
      imageHint: PlaceHolderImages.find(p => p.id === 'product2')?.imageHint || '',
      description: 'Fruity, fun, and uplifting. These sativa-dominant gummies are great for social gatherings and creative boosts.',
      likes: 212,
      dislikes: 12,
      brandId: 'default',
    },
    {
      id: '3',
      name: 'Stardust Suckers',
      category: 'Edibles',
      price: 18.00,
      prices: { '1': 18.00, '2': 19.00, '3': 17.00 },
      imageUrl: PlaceHolderImages.find(p => p.id === 'product3')?.imageUrl || '',
      imageHint: PlaceHolderImages.find(p => p.id === 'product3')?.imageHint || '',
      description: 'Long-lasting, flavorful lollipops with a balanced hybrid effect. Ideal for a steady, manageable high.',
      likes: 98,
      dislikes: 2,
      brandId: 'default',
    },
    {
      id: '4',
      name: 'OG Galaxy',
      category: 'Flower',
      price: 55.00,
      prices: { '1': 55.00, '2': 58.00, '3': 54.00 },
      imageUrl: PlaceHolderImages.find(p => p.id === 'product4')?.imageUrl || '',
      imageHint: PlaceHolderImages.find(p => p.id === 'product4')?.imageHint || '',
      description: 'A classic indica-dominant strain known for its potent relaxing effects and earthy pine aroma. An eighth (3.5g).',
      likes: 450,
      dislikes: 25,
      brandId: 'default',
    },
    {
      id: '5',
      name: 'Nebula Nugs',
      category: 'Flower',
      price: 60.00,
      prices: { '1': 60.00, '2': 62.00, '3': 59.00 },
      imageUrl: PlaceHolderImages.find(p => p.id === 'product5')?.imageUrl || '',
      imageHint: PlaceHolderImages.find(p => p.id === 'product5')?.imageHint || '',
      description: 'Dense, trichome-covered nugs with a sweet and pungent aroma. A premium flower for the discerning connoisseur. An eighth (3.5g).',
      likes: 510,
      dislikes: 15,
      brandId: 'default',
    },
    {
        id: '6',
        name: 'Supernova Haze',
        category: 'Flower',
        price: 58.00,
        prices: { '1': 58.00, '2': 60.00, '3': 57.50 },
        imageUrl: PlaceHolderImages.find(p => p.id === 'product6')?.imageUrl || '',
        imageHint: PlaceHolderImages.find(p => p.id === 'product6')?.imageHint || '',
        description: 'A powerful sativa strain with citrus notes and an energetic, cerebral high. Perfect for daytime use. An eighth (3.5g).',
        likes: 380,
        dislikes: 18,
        brandId: 'default',
    },
    {
        id: '7',
        name: 'Vaporwave Voyage',
        category: 'Vapes',
        price: 45.00,
        prices: { '1': 45.00, '2': 48.00, '3': 44.00 },
        imageUrl: PlaceHolderImages.find(p => p.id === 'product7')?.imageUrl || '',
        imageHint: PlaceHolderImages.find(p => p.id === 'product7')?.imageHint || '',
        description: 'A sleek, disposable vape pen with a balanced hybrid oil. Smooth, flavorful, and discreet. 1g cartridge.',
        likes: 280,
        dislikes: 8,
        brandId: 'default',
    },
    {
        id: '8',
        name: 'Comet Stick',
        category: 'Vapes',
        price: 42.00,
        prices: { '1': 42.00, '2': 45.00, '3': 40.00 },
        imageUrl: PlaceHolderImages.find(p => p.id === 'product8')?.imageUrl || '',
        imageHint: PlaceHolderImages.find(p => p.id === 'vape pen')?.imageHint || '',
        description: 'An indica-dominant vape pen designed for relaxation and sleep. Natural berry flavors. 1g cartridge.',
        likes: 195,
        dislikes: 4,
        brandId: 'default',
    },
     {
        id: '9',
        name: 'Pulsar Pod',
        category: 'Vapes',
        price: 48.00,
        prices: { '1': 48.00, '2': 50.00, '3': 47.00 },
        imageUrl: PlaceHolderImages.find(p => p.id === 'product9')?.imageUrl || '',
        imageHint: PlaceHolderImages.find(p => p.id === 'vape cartridge')?.imageHint || '',
        description: 'A high-potency sativa cartridge with a tangy citrus flavor. Expect an uplifting and creative experience. 1g cartridge.',
        likes: 320,
        dislikes: 10,
        brandId: 'default',
    }
  ];

export const demoRetailers: Retailer[] = [
    {
        id: '1',
        name: 'The Green Spot',
        address: '123 Leafy Lane',
        city: 'Denver',
        state: 'CO',
        zip: '80202',
        phone: '303-123-4567',
        email: 'orders@thegreenspot.com',
        lat: 39.7392,
        lon: -104.9903,
    },
    {
        id: '2',
        name: 'High Altitude Herbs',
        address: '456 Mountain View',
        city: 'Boulder',
        state: 'CO',
        zip: '80302',
        phone: '303-987-6543',
        email: 'orders@highaltitudeherbs.com',
        lat: 40.0150,
        lon: -105.2705,
    },
    {
        id: '3',
        name: 'City Cannabis Collective',
        address: '789 Urban Avenue',
        city: 'Denver',
        state: 'CO',
        zip: '80204',
        phone: '720-555-1212',
        email: 'orders@citycannabisco.com',
        lat: 39.7420,
        lon: -104.9915,
    },
    {
        id: '4',
        name: 'Rocky Mountain Remedies',
        address: '101 Peak Place',
        city: 'Estes Park',
        state: 'CO',
        zip: '80517',
        phone: '970-555-8888',
        email: 'orders@rmremedies.com',
        lat: 40.3772,
        lon: -105.5217,
    }
];
export const demoLocations: Location[] = demoRetailers as Location[];


export const demoCustomer = {
    favoriteRetailerId: '1',
    orders: [
        { id: 'demo1', userId: 'demoUser', createdAt: Timestamp.now(), status: 'completed', totals: { total: 47.50 } },
        { id: 'demo2', userId: 'demoUser', createdAt: Timestamp.now(), status: 'ready', totals: { total: 88.00 } },
    ] as Partial<OrderDoc>[],
    reviews: [
        { id: 'rev1', productId: '1', userId: 'demoUser1', brandId: 'bakedbot-brand-id', rating: 5, text: 'Absolutely love the Cosmic Caramels! Perfect for relaxing after a long day. The taste is amazing and the effects are smooth.', createdAt: Timestamp.fromDate(new Date('2024-05-20T19:30:00Z')) },
        { id: 'rev2', productId: '4', userId: 'demoUser2', brandId: 'bakedbot-brand-id', rating: 4, text: 'OG Galaxy is a classic for a reason. Great for winding down and getting a good night\'s sleep. A bit harsh on the throat sometimes.', createdAt: Timestamp.fromDate(new Date('2024-05-21T12:00:00Z')) },
        { id: 'rev3', productId: '1', userId: 'demoUser3', brandId: 'bakedbot-brand-id', rating: 4, text: 'These are tasty but sometimes inconsistent in potency. One piece was much stronger than another from the same batch.', createdAt: Timestamp.fromDate(new Date('2024-05-22T14:15:00Z')) },
        { id: 'rev4', productId: '2', userId: 'demoUser4', brandId: 'bakedbot-brand-id', rating: 5, text: 'Giggle Gummies are my go-to for social events. They make me feel so talkative and happy without any anxiety. Highly recommend!', createdAt: Timestamp.fromDate(new Date('2024-05-22T18:45:00Z')) },
        { id: 'rev5', productId: '7', userId: 'demoUser1', brandId: 'bakedbot-brand-id', rating: 3, text: 'The Vaporwave Voyage pen is convenient, but the flavor is a bit artificial for my taste. The effects are okay, but not very long-lasting.', createdAt: Timestamp.fromDate(new Date('2024-05-23T09:00:00Z')) },
        { id: 'rev6', productId: '4', userId: 'demoUser5', brandId: 'bakedbot-brand-id', rating: 5, text: 'The best indica I have ever had. Knocks me right out and helps with my insomnia. A true 5-star flower.', createdAt: Timestamp.fromDate(new Date('2024-05-23T21:00:00Z')) },
        { id: 'rev7', productId: '2', userId: 'demoUser2', brandId: 'bakedbot-brand-id', rating: 4, text: 'Fun for a party, but be careful not to take too many! They can be a bit more potent than you expect.', createdAt: Timestamp.fromDate(new Date('2024-05-24T16:20:00Z')) },
        { id: 'rev8', productId: '5', userId: 'demoUser6', brandId: 'bakedbot-brand-id', rating: 5, text: 'Nebula Nugs are absolutely top-tier. The crystal coating is insane and the high is both euphoric and relaxing. Worth every penny.', createdAt: Timestamp.fromDate(new Date('2024-05-25T11:10:00Z')) },
        { id: 'rev9', productId: '9', userId: 'demoUser7', brandId: 'bakedbot-brand-id', rating: 4, text: 'Pulsar Pod gives a great, clean, energetic high. Perfect for getting chores done or going for a hike. Flavor is a little lemony for me.', createdAt: Timestamp.fromDate(new Date('2024-05-26T08:00:00Z')) },
        { id: 'rev10', productId: '6', userId: 'demoUser1', brandId: 'bakedbot-brand-id', rating: 5, text: 'Supernova Haze is a fantastic daytime strain. It really helps me focus and feel creative without any jitters. Has become a staple in my routine.', createdAt: Timestamp.fromDate(new Date('2024-05-27T13:40:00Z')) },
    ] as Partial<Review>[],
    interactions: [
        { brandId: 'default', recommendedProductIds: ['1', '2'] },
        { brandId: 'default', recommendedProductIds: ['4'] }
    ] as Partial<UserInteraction>[],
};
