steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/bakedbot-ai/cloud-run/bakedbot-code-runner'
      - '-f'
      - 'Dockerfile'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/bakedbot-ai/cloud-run/bakedbot-code-runner'
